"""Calculate S1-S3 rider burden metrics from a saved solution."""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

ROOT=Path(__file__).resolve().parent
SRC=ROOT/"03_src"
sys.path.insert(0,str(SRC))

from data_loader import load_instance
from route_evaluator import Route, build_route_timeline
from burden_metrics import RiderBurden, equity_metrics


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--problem",required=True)
    ap.add_argument("--solution",required=True,
                    help="JSON generated by run_baseline.py (checked solution)")
    ap.add_argument("--rider-type",default="BIKE")
    ap.add_argument("--save",default=None)
    args=ap.parse_args()

    inst=load_instance(args.problem)
    rider_map={r.name:r for r in inst.riders}

    with open(args.solution,"r",encoding="utf-8") as f:
        sol=json.load(f)

    burdens=[]
    idx=0
    for rider_type,shop_seq,dlv_seq in sol["bundles"]:
        if rider_type != args.rider_type:
            continue
        rider=rider_map[rider_type]
        route=Route(tuple(shop_seq),tuple(dlv_seq))
        tl=build_route_timeline(inst,route,rider)
        burdens.append(RiderBurden(
            rider_id=f"{rider_type}_{idx:03d}",
            order_count=len(shop_seq),
            active_route_duration_sec=tl.active_route_duration_sec,
            waiting_time_sec=tl.waiting_time_sec,
        ))
        idx += 1

    if not burdens:
        raise RuntimeError(f"No {args.rider_type} routes found in solution.")

    report={
        "problem":inst.name,
        "rider_type":args.rider_type,
        "n_routes":len(burdens),
        "S1_order_count":equity_metrics(burdens,"S1"),
        "S2_active_route_duration":equity_metrics(burdens,"S2"),
        "S3_waiting_time":equity_metrics(burdens,"S3"),
        "rider_burdens":[b.__dict__ for b in burdens],
    }

    print(json.dumps(report,ensure_ascii=False,indent=2))
    if args.save:
        out=Path(args.save)
        out.parent.mkdir(parents=True,exist_ok=True)
        with out.open("w",encoding="utf-8") as f:
            json.dump(report,f,ensure_ascii=False,indent=2)


if __name__=="__main__":
    main()
